services:
  cv-manager-host: localhost
  cv-manager-port: 9092
  file-server-host: localhost
  file-server-port: 9093


server:
  port: 9091

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7070/realms/cv-manager

springdoc:
  swagger-ui:
    oauth:
      client-id: portal-be
      client-secret: eaXaW0Cl3fpvtWhy3fapCf8KdNoPBYl5