version: "3.8"
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: portalDB_mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=bdung
    image: mongo